### ISSUE TITLE
Support for ID3v2.2-2.4 for WAV PCM?

### ISSUE THREAD

**Issue by MagmarFire** [Zeugma440/atldotnet#4]
## The problem

Attempting to read metadata I've set in Audacity from a WAV file results in an empty AdditionalFields dictionary.

## Environment

* ATL version (or git revision) that exhibits the issue: 2.3. The latest revision as of this writing, aab51be8ffe3339854dbb3784c38c1c178cdfd71, also shows this behavior.
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: Windows 10

## Details

I'm writing a music looping system for Unity 3D, and I'm using ATL as the foundation for reading looping metadata *a la* the RPG Maker series of game engines. The idea is that each song is permitted to have two metadata entries indicating the start of a song's loop and how long that loop lasts before the song returns to the start of the loop.

These entries are completely custom tags, and so the assumption is that the AdditionalFields dictionary holds the metadata values. This proves to be behaving as expected with OGGs and AIFF (thus far in my testing), but WAVs are the exception. The tags I define do not appear.

Based on the table that lists the supported types, it appears there is WAV support for ID3v1. According to the [Audacity documentation](https://manual.audacityteam.org/man/faq_opening_and_saving_files.html), Audacity only supports ID3v2. There is evidence to suggest that it once supported ID3v1 years ago but was eclipsed.

I'm unsure if there's anything in the roadmap to supporting ID3v2 for WAV, or if it's even possible considering the problems WAV has with metadata in general, but would it be worthwhile to consider?

**Comment by Zeugma440** [comment]
Fixed by bc02de13f7181270e0436c790339488f513ddadb

**Comment by MagmarFire** [comment]
Thanks for the quick turnaround! Unfortunately, I still have an issue.

I pulled the latest version, rebuilt it, and stuck the updated .dll into my test Unity project. I can confirm that the dictionary is still empty when I attempt to read the metadata from my file.

I'm not sure how much it will help, but I've attached
[White noise with metadata set.wav.txt](https://github.com/Zeugma440/atldotnet/files/1692913/White.noise.with.metadata.set.wav.txt) to give an example of what Audacity exports when we set the metadata there. Simply remove the .txt extension to read it as a .wav. Opening it in Audacity confirms that my custom metadata is set.

If you need me to send a code sample, I can do that, but I'm not sure if it'll be much use.

```C#
public virtual string ReadTrackMetadata(string name)
        {
            string trackPath = AssetDatabase.GetAssetPath(Track);

            if (string.IsNullOrEmpty(trackPath)) return string.Empty;

            Track trackAsset = new Track(trackPath);

            try
            {
                return trackAsset.AdditionalFields[name];
            }
            catch
            {
                Debug.LogWarning(string.Format(@"Field ""{0}"" does not exist for track ""{1}"".", name, Track.name));
                return string.Empty;
            }
        }
```

Please let me know if there's anything else I can provide to give you more insight. Thanks for your help!

**Comment by Zeugma440** [comment]
OK, I see. Thanks for the file !

The implementation used by Audacity is not the standard implementation of ID3v2, but an integration of the ID3v2 structure as a RIFF chunk. ATL has an existing mechanism to handle that. I'll look into it in the following days.

**Comment by Zeugma440** [comment]
Implementation complete, with the proper test file and unit test.

=> 3a5f9bfc7882bd9e733cd3a1774b76dd3c17785a

Thanks for pointing this out @MagmarFire !

**Comment by MagmarFire** [comment]
I got the latest, and I can confirm that it's now working! Thanks a bunch, @Zeugma440!
